// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd9YidWxw6bvQ1X_ZbC8qFsZlROfxO0Es',
    appId: '1:939477585539:web:c51123dab0c010f21515b6',
    messagingSenderId: '939477585539',
    projectId: 'dyhsapp',
    authDomain: 'dyhsapp.firebaseapp.com',
    storageBucket: 'dyhsapp.appspot.com',
    measurementId: 'G-13F8P1FGYB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd59kibSmsZz9-iv8Bau3208HhObA-ZhY',
    appId: '1:939477585539:android:a71b35af41c8dfba1515b6',
    messagingSenderId: '939477585539',
    projectId: 'dyhsapp',
    storageBucket: 'dyhsapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGFTcu2L3QxNclP_erTkLgKRaVasA2Atw',
    appId: '1:939477585539:ios:f0af017cd33b80e41515b6',
    messagingSenderId: '939477585539',
    projectId: 'dyhsapp',
    storageBucket: 'dyhsapp.appspot.com',
    iosClientId: '939477585539-6tu0fd6tinb78qb5il3n74b6u30bcmp5.apps.googleusercontent.com',
    iosBundleId: 'com.dukyoung.dyhsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGFTcu2L3QxNclP_erTkLgKRaVasA2Atw',
    appId: '1:939477585539:ios:f0af017cd33b80e41515b6',
    messagingSenderId: '939477585539',
    projectId: 'dyhsapp',
    storageBucket: 'dyhsapp.appspot.com',
    iosClientId: '939477585539-6tu0fd6tinb78qb5il3n74b6u30bcmp5.apps.googleusercontent.com',
    iosBundleId: 'com.dukyoung.dyhsapp',
  );
}
